---
name: LoadAllWorlds
version: 1.1.3
main: koningcool\loadallworlds\Main
api: 4.2.6

commands:
  loadworlds:
    description: Load the worlds in the server, excluding the specified worlds in the config.yml
    permission: loadallworlds.loadworlds.command
  loadall:
    description: Load all the worlds in the server
    aliases: [loadallworlds,law]
    permission: loadallworlds.command

permissions:
  loadallworlds.loadworlds.command:
    description: "Allows the user to run the command"
    default: true

  loadallworlds.command:
    description: "Allows the user to run the command"
    default: true

...
