---
name: LoadAllWorlds
version: 1.1.2
main: koningcool\loadallworlds\Main
api: 3.12.0

commands:
  loadworlds:
    description: Load the worlds in the server, excluding the specified worlds in the config.yml
    permission: loadallworlds.loadworlds.command
  loadall:
    description: Load all the worlds in the server
    permission: loadallworlds.command
    aliases: [loadallworlds,law] 
...
