---
name: LoadAllWorlds
version: 0.0.6
main: koningcool\loadallworlds\Main
api: 3.12.0

commands:
  loadall:
    description: Load all the worlds in the server!
    permission: loadallworlds.command
    aliases: [loadallworlds,loadworlds,worldloader,law] 
...
